[package]
name = "asmov-testing"
authors = ["Asmov LLC <devolopment.pub@asmov.software>"]
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
function_name = "0"
futures = "0"
lazy_static = "1"
once_cell = "1"
rand = "0"
regex = "1"
shutdown_hooks = "0"
sysinfo = "0"
